replicaCount: 2

autoscaling:
  enabled: false

image:
  repository: flask-db        # built inside Minikube Docker
  tag: env
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000                       # Flask listens on 5000

# Container port & probes will use this
livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

env:
  - name: APP_MESSAGE
    value: "This is flask docker app from ENV"
  - name: DB_HOST
    value: "db-service"
  - name: DB_USER
    value: "bmwadmin"
  - name: DB_PASSWORD
    value: "admin123"

resources:
  limits:
    cpu: "250m"
    memory: "250Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoExecute"

serviceAccount:
  create: false
  name: ""
  annotations: {}

